### ISSUE TITLE
pac tool and Cl3 tool issue

### ISSUE THREAD

**Issue by huaixuyang** [MysteryDash/MysteryDash.FileFormats#1]
pac Builder tool:
I unpacked the GAME00005.pac ,and repacked it with your pac Builder.exe tool(Game title image is in this file).
After replaced the original GAME00005.pac,I started the game,and the title screen become black,and game frozen.

cl3 tool:
I used to replace the cl3 file by using nr1_packer.exe,and it worked
For example,I renamed the GAME00001\chara\001\texture\002.cl3(The black texture of neptune`s cloth ) to 001.cl3
and replaced the original 001.cl3 in GAME00001.pac with it.
The game works well,and neptune`s original cloth become black.
But when I try to replace the original cl3 file with the cl3 that repacked by your tools,the game crashed.

I compared the the original cl3 file,and the cl3 that repacked by your tool ,the size is different.

**Comment by MysteryDash** [comment]
Do you have any other tool to repack the CL3 ? If so, can you send it to me ?
It was expected that the CL3 could cause harm because of the FILE_LINK section that is left empty. As for the reason why it is left empty it's because although I know how this section work the links linking the files together looks like it is done manually. The good news is that I may be able to create a replacer for the .PAC and the .CL3, that means that the compression will be kept for the .PAC and that the links will be kept for the .CL3, and that way it should work.  
I know it may take some time but I have barely an hour to work on this today and tomorrow will not be a day on which I can work, so I'll try to make it ASAP but I don't promise anything.

**Comment by huaixuyang** [comment]
I`m sorry,
But I have no other tools to repack the cl3.

**Comment by MysteryDash** [comment]
That's good to know then.
I'll upload things in at least two days as my current work-time is over.
I'll run my own tests so that it doesn't happen anymore. I shouldn't have released this without at least trying to mod the game (I only did packing/extraction tests which were, of course, all successful).

**Comment by MysteryDash** [comment]
Fixed.
